name: C/C++ CI

on:

  push:
    paths:
    - src/**
    - .github/workflows/**

  pull_request:
    paths:
    - src/**
    - .github/workflows/**

jobs:
  build:

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    strategy:

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: MINGW32
        install: 'make mingw-w64-i686-toolchain mingw-w64-i686-openal mingw-w64-i686-freetype mingw-w64-i686-SDL2 mingw-w64-i686-zlib mingw-w64-i686-libpng mingw-w64-i686-libvncserver'
    - uses: actions/checkout@v2
    - name: make
      run: make -fwin/makefile.mingw DEV_BUILD=y NEW_DYNAREC=y VNC=n
      working-directory: ./src
